"""Add metric context fields

Revision ID: 0dcb44b17d0f
Revises: 071318db2ff1
Create Date: 2026-08-05 17:10:47.118444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcb44b17d0f'
down_revision = '071318db2ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurement_period_days', sa.Integer(), server_default='30', nullable=False))
        batch_op.add_column(sa.Column('data_coverage_percent', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('data_coverage_percent')
        batch_op.drop_column('measurement_period_days')

    # ### end Alembic commands ###
