"""Create external identities table

Revision ID: 1f26b9561d6c
Revises: 4555390581bd
Create Date: 2026-09-20 14:00:43.164804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f26b9561d6c'
down_revision = '4555390581bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_identities',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('data_source_id', sa.String(length=50), nullable=False),
    sa.Column('external_user_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'external_user_id', name='uq_external_identity_source_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_identities')
    # ### end Alembic commands ###
