"""Add encrypted integration tokens

Revision ID: 4555390581bd
Revises: 5d514762efb4
Create Date: 2026-09-05 18:57:29.300666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4555390581bd'
down_revision = '5d514762efb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('refresh_token_encrypted')
        batch_op.drop_column('access_token_encrypted')

    # ### end Alembic commands ###
